version: '3'
services:
  app_5001:
    build:
      context: .
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production

  app_5002:
    build:
      context: .
    ports:
      - "5002:5000"
    environment:
      NODE_ENV: production