version: '3'
services:
  es01:
    image: elasticsearch:8.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_VM_MAX_MAP_COUNT=262144"
    #      - xpack.security.enabled=true  # SSL/TLS
    #      - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - wagglewaggle_network

  app_5001:
    build:
      context: .
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
    networks:
      - wagglewaggle_network

  app_5002:
    build:
      context: .
    ports:
      - "5002:5000"
    environment:
      NODE_ENV: production
    networks:
      - wagglewaggle_network

volumes:
  data01: {}

networks:
  wagglewaggle_network: