name: Lint CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint
        if: ${{ always() }}

      - name: Build
        run: npm run build
        if: ${{ always() }}
